services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: neostore_backend
    environment:
      JAVA_OPTS: "-Djboss.bind.address=0.0.0.0"
    ports:
      - "8080:8080"
    networks:
      - neostore-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: neostore_frontend
    environment:
      VITE_API_URL: http://backend:8080/neostore/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - neostore-net
    restart: unless-stopped

networks:
  neostore-net:
    driver: bridge